version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: sbarito 
      POSTGRES_PASSWORD: sbarito
      POSTGRES_DB: 1_laba     
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./исходные данные:/data"
      - ./mock_data:/docker-entrypoint-initdb.d  
    restart: unless-stopped

volumes:
  postgres_data: